FROM fedora:37

RUN dnf -y update \
    && dnf -y install \
        cmake \
        git \
        gcc-c++ \
        gcc-gfortran \
        lcov \
        make \
        netcdf-fortran-devel \
        valgrind \
        yaml-cpp-devel \
    && dnf clean all

# copy the musica core code
COPY . /musica-core/

# get a tag and build the model
RUN mkdir /build \
    && cd /build \
    && cmake -D CMAKE_BUILD_TYPE=COVERAGE \
             -D ENABLE_COVERAGE:BOOL=TRUE \
             -D ENABLE_YAML=ON \
             ../musica-core \
    && make \
    && make install
