name: build

on: [push, pull_request]

jobs:
  build_test_no_mpi_no_memcheck:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build Docker image
      run: docker build -t musica-core-test .
    - name: run tests in container
      run: docker run --name test-container -t musica-core-test bash -c 'cd build; make coverage ARGS="--rerun-failed --output-on-failure"'
    - name: copy coverage from container
      run: docker cp test-container:build/coverage.info .
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.info
  build_util_only:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build Docker image for util-only tests
      run: docker build -t musica-core-util-test . -f Dockerfile.util
    - name: run MPI tests in container
      run: docker run -t musica-core-util-test bash -c 'cd build; make test ARGS="--rerun-failed --output-on-failure"'
  build_mpi:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build Docker image for MPI tests
      run: docker build -t musica-core-mpi-test . -f Dockerfile.mpi
    - name: run MPI tests in container
      run: docker run -t musica-core-mpi-test bash -c 'cd build; make test ARGS="--rerun-failed --output-on-failure"'
  build_util_only_mpi:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build Docker image for util-only MPI tests
      run: docker build -t musica-core-util-mpi-test . -f Dockerfile.util.mpi
    - name: run MPI tests in container
      run: docker run -t musica-core-util-mpi-test bash -c 'cd build; make test ARGS="--rerun-failed --output-on-failure"'